#!/usr/bin/env bash

# File parameters
INPUT_FILE=""
INPUT_DIR=""
OUTPUT_FILE=""

# Compiler parameters
COMPILER=""
COMPILER_OPTS=""
PROGRAM_OPTS=""
MAKEFILE=""

# Error parameters
ERRS=0

run_ghci_compiler() {
  OUTPUT_FILE="${INPUT_FILE%.*}"

  if [ $FLAG_G ]; then
    GHCI_COMMAND="ghci $COMPILER_OPTS $INPUT_FILE"
  else
    GHCI_COMMAND="ghc "$COMPILER_OPTS" -o "$OUTPUT_FILE" "$INPUT_FILE""
  fi
  
  echo CMD: "$GHCI_COMMAND"
  
  $GHCI_COMMAND
}

run_clng_compiler() {
  OUTPUT_FILE="${INPUT_FILE%.*}"

  CLNG_COMMAND="clang $COMPILER_OPTS $INPUT_FILE -o $OUTPUT_FILE -fsanitize=undefined -fsanitize=address"
  
  echo CMD: "$CLNG_COMMAND"
  
  $CLNG_COMMAND
}

run_make_compiler() {
  cd $INPUT_DIR

  OUTPUT_FILE="${INPUT_FILE%.*}"
  MAKE="${OUTPUT_FILE#"$INPUT_DIR/"}"
  MAKE_COMMAND="make $MAKE"

  echo "CMD: $MAKE_COMMAND"
  
  $MAKE_COMMAND
}

usage() {
  cat compile.txt | less
}

H_OPTS="gh:"
C_OPTS="mc:"
G_OPTS="i:a:r"

while getopts ":$H_OPTS$C_OPTS$G_OPTS" opts; do 

  case "${opts}" in 
    # Haskell Options
    h)
      FLAG_H=1
      INPUT_FILE="$OPTARG"
      COMPILER=run_ghci_compiler
      ;;
    g)
      FLAG_G=1
      ;;
    # C Options
    c)
      FLAG_C=1
      INPUT_FILE="$OPTARG"
      INPUT_DIR="${INPUT_FILE%/*}"
      INPUT_DIR_CONTENTS=$(dir $INPUT_DIR)

      for file in $INPUT_DIR_CONTENTS; do 
        if [[ " $file " =~ .*\ Makefile\ .* ]]; then
          MAKEFILE=1
          break
        fi
      done;

      if [[ "$MAKEFILE" && $FLAG_M ]]; then
        COMPILER=run_make_compiler
      else
        COMPILER_OPTS="-std=c11 -Wall -pedantic -g"
        COMPILER=run_clng_compiler
      fi
      ;;
    m)
      FLAG_M=1
      ;;
    # Global Options
    i)
      FLAG_I=1
      COMPILER_OPTS="$COMPILER_OPTS $OPTARG"
      ;;
    r)
      FLAG_R=1
      ;;
    a)
      FLAG_A=1
      PROGRAM_OPTS="$OPTARG"
      ;;
    # Other Options
    \?) 
      echo "Something is weird"
      ;;
    *)
      echo "Something is even weirder."
      ;;
  esac

done

if [ ! $1 ]; then
  usage
  exit 1
fi

if [ ! "$COMPILER" ]; then
  echo "There seems to be an error - did specify the -h or -c option?"
  ERRS=$((ERRS + 1))
fi

if [ ! "$INPUT_FILE" ]; then 
  echo "An input file is needed to continue"
  ERRS=$((ERRS + 1))
fi

if [ ! -f "$INPUT_FILE" ]; then
  echo "File not found: $INPUT_FILE"
  ERRS=$((ERRS + 1))
fi

if [[ ERRS -gt 0 ]]; then
  echo "WRN: $ERRS errors occured."
  exit 1
fi

if [[ -f %OUTPUT_FILE ]]; then 
  rm -rf $OUTPUT_FILE
fi

"$COMPILER" "$INPUT_FILE"


if [ "$FLAG_R" ]; then
  echo CMD: "$OUTPUT_FILE $PROGRAM_OPTS"
  $OUTPUT_FILE $PROGRAM_OPTS
fi

exit 0